import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import { FaGithub } from "react-icons/fa6";

// Components
import Navigation from "./(dashboard)/Navigation";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next App with Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-100">
      <body className="d-flex flex-column h-100">
        <header>
          <Navigation />
        </header>
        <main className="flex-shrink-0">
          <div className="container-fluid">
            {children}
            <Toaster />
          </div>
        </main>
        <footer className="footer mt-auto py-3 bg-body-tertiary text-center">
          <span className="text-body-secondary">
            <small>&copy; {new Date().getFullYear()} Company, Inc.</small>
          </span>
          <br />
          <a
            style={{ color: "#777" }}
            href="https://github.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaGithub />
          </a>{" "}
          <small>
            <span className="text-body-secondary">v0.2.0</span>
          </small>
        </footer>
      </body>
    </html>
  );
}
