import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

// Components
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default async function AuthLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });
  const { data } = await supabase.auth.getSession();
  if (data.session) {
    redirect("/");
  }

  return (
    <body className="d-flex flex-column h-100 bg-body-tertiary">
      <main className="flex-shrink-0">
        {children}
        <Toaster />
      </main>
      <footer className="mt-auto py-3 text-center text-body-secondary">
        <small>&copy; {new Date().getFullYear()} Lorenesi y Cia. Ltda.</small>
      </footer>
    </body>
  );
}
